// Generates THIRD_PARTY_NOTICES.md from what is really bundled: esbuild's metafile lists every node_modules package that ends up in
// the extension, plus the Inter font files copied from @fontsource-variable/inter. Run: npm run notices
import { build } from 'esbuild';
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const proj = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const entries = { background: 'src/background/index.ts', offscreen: 'src/offscreen/index.ts', sidepanel: 'src/sidepanel/index.ts', review: 'src/review/index.ts' };
const common = { bundle: true, write: false, metafile: true, outdir: path.join(proj, '.notices-tmp'), target: 'chrome116', define: { __E2E__: 'false' }, loader: { '.svg': 'text' }, logLevel: 'silent', absWorkingDir: proj };
const metas = [
  (await build({ ...common, entryPoints: entries, format: 'esm' })).metafile,
  (await build({ ...common, entryPoints: { content: 'src/content/index.ts' }, format: 'iife' })).metafile,
];
const roots = new Set();
for (const m of metas) for (const f of Object.keys(m.inputs)) {
  if (f.startsWith('(disabled)')) continue; // modules esbuild replaced with an empty stub (browser field)
  const i = f.lastIndexOf('node_modules/');
  if (i < 0) continue;
  const rest = f.slice(i + 'node_modules/'.length).split('/');
  roots.add(path.join(proj, f.slice(0, i), 'node_modules', rest[0].startsWith('@') ? `${rest[0]}/${rest[1]}` : rest[0]));
}
roots.add(path.join(proj, 'node_modules', '@fontsource-variable', 'inter'));
// docx ships as one pre-bundled file that inlines its own dependency tree (esbuild therefore cannot see it); list those explicitly.
const INLINED_IN_DOCX = ['jszip', 'pako', 'lie', 'immediate', 'readable-stream', 'core-util-is', 'inherits', 'isarray', 'process-nextick-args', 'safe-buffer', 'string_decoder', 'util-deprecate', 'setimmediate', 'hash.js', 'minimalistic-assert', 'nanoid', 'xml', 'xml-js', 'sax'];
const embedded = new Set();
for (const n of INLINED_IN_DOCX) {
  const d = path.join(proj, 'node_modules', n);
  if (existsSync(path.join(d, 'package.json')) && !roots.has(d)) { roots.add(d); embedded.add(d); }
} // the bundled woff2 files in public/fonts come from here

const pkgs = [...roots].map((dir) => {
  const j = JSON.parse(readFileSync(path.join(dir, 'package.json'), 'utf8'));
  const lf = readdirSync(dir).find((n) => /^(licen[sc]e|copying)(\.|$)/i.test(n));
  const repo = typeof j.repository === 'string' ? j.repository : j.repository?.url ?? j.homepage ?? '';
  return { embedded: embedded.has(dir), name: j.name, version: j.version, license: typeof j.license === 'string' ? j.license : JSON.stringify(j.license ?? j.licenses ?? 'see package'), home: j.homepage ?? repo, repo: repo.replace(/^git\+/, '').replace(/\.git$/, ''), text: lf ? readFileSync(path.join(dir, lf), 'utf8').trim() : '' };
}).sort((a, b) => a.name.localeCompare(b.name));

const src = (p) => (/mpl/i.test(p.license) ? `\nSource code of this package (MPL-2.0 is file-level; it is bundled unmodified): ${p.repo || p.home}\n` : '');
let md = `# Third-party notices

ReproDesk bundles the open-source components below. This file is generated by \`npm run notices\` from the packages that actually end up
in the extension bundle (and the Inter font files shipped in \`fonts/\`). ReproDesk itself is not covered by these licences.

| Package | Version | Licence | Used for |
|---|---|---|---|
${pkgs.map((p) => `| ${p.name} | ${p.version} | ${p.license} | ${({ docx: 'Word (.docx) export', fflate: 'ZIP / XLSX packaging, SHA-256 manifest input', 'lucide-static': 'UI icons (inlined SVG)', mediabunny: 'WebM muxing of the replay', '@fontsource-variable/inter': 'Inter variable font (bundled, no web request)' })[p.name] ?? (p.embedded ? 'embedded in the docx build' : 'transitive dependency')} |`).join('\n')}

Licence texts below are those of the installed copies. \`jszip\` is dual-licensed (MIT or GPL-3.0-or-later); ReproDesk uses it under the MIT terms.

Icons are from [Lucide](https://lucide.dev); the font is [Inter](https://rsms.me/inter/) by The Inter Project Authors, licensed under the SIL Open Font License 1.1.

---
${pkgs.map((p) => `\n## ${p.name} ${p.version}\n\nLicence: ${p.license} · ${p.home}\n${src(p)}\n${p.text ? '```text\n' + p.text + '\n```' : '_No licence file shipped with the package; see the link above._'}\n`).join('\n')}`;
writeFileSync(path.join(proj, 'THIRD_PARTY_NOTICES.md'), md);
console.log(`THIRD_PARTY_NOTICES.md: ${pkgs.length} packages -> ${pkgs.map((p) => p.name + '@' + p.version + ' (' + p.license + ')').join(', ')}`);
